package com.example.home_recipe.global.response

enum class ResponseCode(val code: String, val message: String) {

    SIGNUP_SUCCESS("SIGNUP_SUCCESS", "회원가입 성공"),
    SIGNUP_ERROR_001("SIGNUP_ERROR_001", "필수 필드 누락"),
    SIGNUP_ERROR_002("SIGNUP_ERROR_002", "이름이 너무 짧거나 김"),
    SIGNUP_ERROR_003("SIGNUP_ERROR_003", "비밀번호 정책 불일치"),
    SIGNUP_ERROR_004("SIGNUP_ERROR_004", "이메일 형식 오류"),
    SIGNUP_ERROR_005("SIGNUP_ERROR_005", "중복된 이메일"),
    SIGNUP_ERROR_006("SIGNUP_ERROR_006", "약관 동의 누락"),

    LOGIN_SUCCESS("LOGIN_SUCCESS", "로그인 성공"),
    LOGIN_ERROR_001("LOGIN_ERROR_001", "필수 필드 누락"),
    LOGIN_ERROR_002("LOGIN_ERROR_002", "존재하지 않는 아이디"),
    LOGIN_ERROR_003("LOGIN_ERROR_003", "비밀번호 불일치"),

    AUTH_SUCCESS("AUTH_SUCCESS", "토큰 검증 성공"),
    AUTH_ERROR_001("AUTH_ERROR_001", "Access Token 누락"),
    AUTH_ERROR_002("AUTH_ERROR_002", "Access Token 만료"),
    AUTH_ERROR_003("AUTH_ERROR_003", "Access Token 위조"),
    AUTH_ERROR_004("AUTH_ERROR_004", "Refresh Token 누락"),
    AUTH_ERROR_005("AUTH_ERROR_005", "Refresh Token 만료"),
    AUTH_ERROR_006("AUTH_ERROR_006", "Refresh Token 위조"),

    REFRIGERATOR_SUCCESS("REFRIGERATOR_SUCCESS", "냉장고 조회 성공"),
    REFRIGERATOR_ERROR_001("REFRIGERATOR_ERROR_001", "요청 파라미터 오류"),
    REFRIGERATOR_ERROR_002("REFRIGERATOR_ERROR_002", "로그인하지 않음"),
    REFRIGERATOR_ERROR_003("REFRIGERATOR_ERROR_003", "다른 사용자의 냉장고 접근"),
    REFRIGERATOR_ERROR_004("REFRIGERATOR_ERROR_004", "냉장고 없음"),

    INGREDIENT_SUCCESS("INGREDIENT_SUCCESS", "재료 추가 성공"),
    INGREDIENT_ERROR_005("INGREDIENT_ERROR_005", "재료명 누락"),
    INGREDIENT_ERROR_006("INGREDIENT_ERROR_006", "비로그인 요청"),
    INGREDIENT_ERROR_007("INGREDIENT_ERROR_007", "다른 사용자 냉장고 접근"),
    INGREDIENT_ERROR_008("INGREDIENT_ERROR_008", "잘못된 재료 ID"),
    INGREDIENT_ERROR_011("INGREDIENT_ERROR_011", "해당 재료 없음"),

    RECIPE_SUCCESS("RECIPE_SUCCESS", "레시피 생성 성공"),
    RECIPE_ERROR_001("RECIPE_ERROR_001", "요청 형식 오류"),
    RECIPE_ERROR_002("RECIPE_ERROR_002", "비로그인 요청"),
    RECIPE_ERROR_003("RECIPE_ERROR_003", "다른 사용자 냉장고 접근"),
    RECIPE_ERROR_004("RECIPE_ERROR_004", "냉장고 정보 없음"),

    RECOMMENDATION_SUCCESS("RECOMMENDATION_SUCCESS", "추천 성공"),
    RECOMMENDATION_ERROR_001("RECOMMENDATION_ERROR_001", "요청 형식 오류"),
    RECOMMENDATION_ERROR_002("RECOMMENDATION_ERROR_002", "비로그인 요청"),
    RECOMMENDATION_ERROR_003("RECOMMENDATION_ERROR_003", "다른 사용자 냉장고 접근"),
    RECOMMENDATION_ERROR_004("RECOMMENDATION_ERROR_004", "냉장고 정보 없음")
}
